import React, { useState, useEffect } from 'react';
import PageContainer from '../layout/PageContainer';
import Navbar from '../layout/Navbar';
import { API_BASE_URL } from '../data/constants';
import { PieChart, Pie, Cell, Tooltip, BarChart, Bar, XAxis, YAxis, ResponsiveContainer } from 'recharts';

const Reports = () => {
  const [reportsData, setReportsData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReportsData = async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/reports`);
        if (response.ok) {
          const data = await response.json();
          setReportsData(data);
        }
      } catch (error) {
        console.error("Failed to fetch reports data:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchReportsData();
  }, []);

  // Download individual row report
  const handleDownloadReport = (report) => {
    const csvContent = "data:text/csv;charset=utf-8," 
      + "Report Name,Type,Generated By,Date,Format,Status\n"
      + `"${report.name}","${report.type}","${report.generatedBy}","${report.date}","${report.format}","${report.status}"`;
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${report.name.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // --- UPDATED: Master Export Function for the entire dashboard ---
  const handleExportDashboard = async () => {
    if (!reportsData) return;

    let csvContent = "data:text/csv;charset=utf-8,";
    
    // 1. Add Dashboard KPIs
    csvContent += "DASHBOARD SUMMARY\n";
    csvContent += `Total Contracts,${reportsData.kpi.total}\n`;
    csvContent += `Compliant Contracts,${reportsData.kpi.compliant}\n`;
    csvContent += `Expiring Soon,${reportsData.kpi.expiring}\n`;
    csvContent += `Overdue Contracts,${reportsData.kpi.overdue}\n`;
    
    // We strip commas from the dollar amounts so it doesn't break the CSV columns
    csvContent += `Total Contract Value,${reportsData.valueSummary.total.replace(/,/g, '')}\n\n`;

    // 2. Add Recent Reports Data
    csvContent += "REPORT HISTORY\n";
    csvContent += "Report Name,Type,Generated By,Date,Format,Status\n";
    
    reportsData.recentReports.forEach(report => {
      csvContent += `"${report.name}","${report.type}","${report.generatedBy}","${report.date}","${report.format}","${report.status}"\n`;
    });

    // 3. Trigger the Download
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    
    const today = new Date();
    const todayISO = today.toISOString().split('T')[0];
    
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `ContractIQ_Dashboard_Export_${todayISO}.csv`);
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // 4. Save the export action to the live PostgreSQL database
    try {
      const storedUser = JSON.parse(localStorage.getItem('user'));
      const userName = storedUser?.name || 'Guest User';
      
      const dateString = today.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

      await fetch(`${API_BASE_URL}/reports/history`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: `Dashboard Snapshot - ${dateString}`,
          type: 'Dashboard',
          generatedBy: userName,
          date: dateString,
          format: 'CSV',
          status: 'Completed'
        })
      });

      // Refetch the data so the new row appears in the UI instantly
      const response = await fetch(`${API_BASE_URL}/reports`);
      if (response.ok) {
        const data = await response.json();
        setReportsData(data);
      }
    } catch (error) {
      console.error("Failed to save report history to database", error);
    }
  };

  if (loading || !reportsData) return <PageContainer><div>Loading Reports Dashboard...</div></PageContainer>;

  return (
    <PageContainer>
      <Navbar />

      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <div>
          <h2>Reports Dashboard</h2>
          <p>Track, analyze and export your contract and compliance reports.</p>
        </div>
        <button onClick={handleExportDashboard} style={{ padding: '8px 16px', background: '#5f27cd', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
          📥 Export Report
        </button>
      </div>

      {/* KPI Row */}
      <div style={{ display: 'flex', gap: '20px', marginBottom: '20px' }}>
        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ color: '#888', marginBottom: '10px' }}>Total Contracts</h4>
          <h2 style={{ fontSize: '2rem', color: '#5f27cd' }}>{reportsData.kpi.total}</h2>
        </div>
        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ color: '#888', marginBottom: '10px' }}>Compliant Contracts</h4>
          <h2 style={{ fontSize: '2rem', color: '#2ecc71' }}>{reportsData.kpi.compliant}</h2>
        </div>
        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ color: '#888', marginBottom: '10px' }}>Expiring Soon</h4>
          <h2 style={{ fontSize: '2rem', color: '#f39c12' }}>{reportsData.kpi.expiring}</h2>
        </div>
        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ color: '#888', marginBottom: '10px' }}>Overdue Contracts</h4>
          <h2 style={{ fontSize: '2rem', color: '#e74c3c' }}>{reportsData.kpi.overdue}</h2>
        </div>
      </div>

      {/* Middle Charts Row */}
      <div style={{ display: 'flex', gap: '20px', marginBottom: '20px' }}>
        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ marginBottom: '15px' }}>Contract Status Overview</h4>
          <div style={{ height: 200 }}>
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={reportsData.statusChart} innerRadius={60} outerRadius={80} dataKey="value">
                  {reportsData.statusChart.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ marginBottom: '15px' }}>Contracts by Department</h4>
          <div style={{ height: 200 }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart layout="vertical" data={reportsData.departmentChart} margin={{ top: 0, right: 20, left: -20, bottom: 0 }}>
                <XAxis type="number" hide />
                <YAxis dataKey="name" type="category" axisLine={false} tickLine={false} />
                <Tooltip />
                <Bar dataKey="value" fill="#5f27cd" radius={[0, 4, 4, 0]} barSize={15} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ marginBottom: '15px' }}>Contract Value Summary</h4>
          <h2 style={{ fontSize: '2rem', marginBottom: '5px' }}>{reportsData.valueSummary.total}</h2>
          <p style={{ color: '#888', fontSize: '12px', marginBottom: '20px' }}>Total Contract Value</p>
          
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px', fontSize: '14px' }}>
            <span style={{ color: '#555' }}>Average Contract Value</span>
            <strong>{reportsData.valueSummary.average}</strong>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px', fontSize: '14px' }}>
            <span style={{ color: '#555' }}>Highest Contract Value</span>
            <strong>{reportsData.valueSummary.highest}</strong>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '14px' }}>
            <span style={{ color: '#555' }}>Lowest Contract Value</span>
            <strong>{reportsData.valueSummary.lowest}</strong>
          </div>
        </div>

        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ marginBottom: '15px' }}>Reports by Type</h4>
          <div style={{ height: 200 }}>
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={reportsData.typeChart} innerRadius={60} outerRadius={80} dataKey="value">
                  {reportsData.typeChart.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Bottom Row: Table & Insights */}
      <div style={{ display: 'flex', gap: '20px' }}>
        <div className="card" style={{ flex: 3 }}>
          <h4 style={{ marginBottom: '15px' }}>Recent Reports</h4>
          <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid #eee' }}>
                <th style={{ padding: '10px 0' }}>Report Name</th>
                <th>Type</th>
                <th>Generated By</th>
                <th>Generated On</th>
                <th>Format</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {reportsData.recentReports.map((report) => (
                <tr key={report.id} style={{ borderBottom: '1px solid #f8f9fa' }}>
                  <td style={{ padding: '15px 0', fontWeight: 'bold' }}>{report.name}</td>
                  <td>{report.type}</td>
                  <td>{report.generatedBy}</td>
                  <td>{report.date}</td>
                  <td style={{ color: report.format === 'PDF' ? '#e74c3c' : '#2ecc71', fontWeight: 'bold' }}>
                    {report.format}
                  </td>
                  <td><span style={{ background: '#e8f8f5', color: '#2ecc71', padding: '4px 10px', borderRadius: '12px', fontSize: '12px' }}>{report.status}</span></td>
                  <td>
                    <button onClick={() => handleDownloadReport(report)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#5f27cd', fontSize: '18px' }}>📥</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="card" style={{ flex: 1 }}>
          <h4 style={{ marginBottom: '15px' }}>Report Insights</h4>
          <ul style={{ listStyle: 'none', padding: 0 }}>
            {reportsData.insights.map((insight, index) => (
              <li key={index} style={{ display: 'flex', gap: '15px', marginBottom: '20px' }}>
                <div style={{ background: `${insight.color}20`, color: insight.color, width: '40px', height: '40px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '20px' }}>
                  {insight.icon}
                </div>
                <div>
                  <strong style={{ display: 'block', fontSize: '14px', marginBottom: '3px' }}>{insight.title}</strong>
                  <span style={{ fontSize: '12px', color: '#888' }}>{insight.subtext}</span>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </PageContainer>
  );
};

export default Reports;