const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const targetPath = path.join(__dirname, 'src', 'environments', 'environment.ts');

let apiUrl = 'http://localhost:8000/api';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const lines = envContent.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx !== -1) {
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      if (key === 'API_URL') {
        apiUrl = val.replace(/(^['"]|['"]$)/g, '');
      }
    }
  }
} else {
  console.log('No local .env file found. Creating one with default API_URL...');
  fs.writeFileSync(envPath, 'API_URL=http://localhost:8000/api\n', 'utf8');
}

const envFileContent = `// This file is auto-generated by set-env.js
export const environment = {
  production: false,
  apiUrl: '${apiUrl}'
};
`;

// Ensure directory exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)){
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(targetPath, envFileContent, 'utf8');
console.log(`Generated environment.ts with API_URL: ${apiUrl}`);
