// Professional icon set, powered by lucide-react (clean, consistent
// stroke icons) instead of hand-drawn SVG paths. Every export keeps the
// exact same name it had before, so Sidebar.js / Navbar.js / Settings.js /
// every page that imports from here needs zero other changes.
//
// Requires: npm install lucide-react (already added to package.json).
export {
  LayoutGrid as GridIcon,
  FileText as FileIcon,
  ClipboardList as ClipboardIcon,
  Repeat as RepeatIcon,
  Shield as ShieldIcon,
  BarChart2 as BarIcon,
  Bell as BellIcon,
  BookOpen as BookIcon,
  Users as UsersIcon,
  Settings as GearIcon,
  ChevronDown as ChevDownIcon,
  ChevronLeft as ChevLeftIcon,
  ChevronRight as ChevRightSmIcon,
  Search as SearchIcon,
  Calendar as CalendarIcon,
  Moon as MoonIcon,
  Sun as SunIcon,
  HelpCircle as HelpIcon,
  Plus as PlusIcon,
  User as UserIcon,
  Bell as BellSmIcon,
  ArrowLeftRight as SwitchIcon,
  LogOut as LogoutIcon,
  Edit2 as EditIcon,
  Check as CheckIcon,
  CheckCircle as CheckCircleIcon,
  AlertTriangle as AlertTriIcon,
  Info as InfoIcon,
  ClipboardCheck as ClipboardCheckIcon,
  Plug as PlugIcon,
  Send as SendIcon,
  Download as DownloadIcon,
  Briefcase as BriefcaseIcon,
  Building2 as BuildingIcon,
  Lock as LockIcon,
  X as XIcon,
  Menu as MenuIcon,
  Zap as ZapIcon,
  HelpCircle as HelpCircleIcon,
  Camera as CameraIcon,
  Play as PlayIcon,
  CreditCard as CreditCardIcon,
  Trash as TrashIcon,
  Key as KeyIcon,
} from "lucide-react";
